<a href="https://colab.research.google.com/github/Kedhar034/Recommedation-system-project/blob/main/Recommendation_system_using_ML_with_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing dependencies


In [1]:
import numpy as np
import pandas as pd
import difflib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [2]:
# loading from data from the csv file to apandas dataframe
movies_data= pd.read_csv('/content/drive/MyDrive/Recommendation system/Excel 15K.csv')


In [3]:
# printing the first 5 rows of dataframe
movies_data.head()

Index  adult                              belongs_to_collection    budget  \
0      0  False  {'id': 10194, 'name': 'Toy Story Collection', ...  30000000   
1      1  False                                                NaN  65000000   
2      2  False  {'id': 119050, 'name': 'Grumpy Old Men Collect...         0   
3      3  False                                                NaN  16000000   
4      4  False  {'id': 96871, 'name': 'Father of the Bride Col...         0   

                                              genres  \
0  [{'id': 16, 'name': 'Animation'}, {'id': 35, '...   
1  [{'id': 12, 'name': 'Adventure'}, {'id': 14, '...   
2  [{'id': 10749, 'name': 'Romance'}, {'id': 35, ...   
3  [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...   
4                     [{'id': 35, 'name': 'Comedy'}]   

                               homepage     id    imdb_id original_language  \
0  http://toystory.disney.com/toy-story    862  tt0114709                en   
1                                   NaN   8844  tt0113497                en   
2                                   NaN  15602  tt0113228                en   
3                                   NaN  31357  tt0114885                en   
4                                   NaN  11862  tt0113041                en   

                original_title  ...     release_date    revenue runtime  \
0                    Toy Story  ...  10/30/1995 0:00  373554033    81.0   
1                      Jumanji  ...  12/15/1995 0:00  262797249   104.0   
2             Grumpier Old Men  ...  12/22/1995 0:00          0   101.0   
3            Waiting to Exhale  ...  12/22/1995 0:00   81452156   127.0   
4  Father of the Bride Part II  ...   2/10/1995 0:00   76578911   106.0   

                                    spoken_languages    status  \
0           [{'iso_639_1': 'en', 'name': 'English'}]  Released   
1  [{'iso_639_1': 'en', 'name': 'English'}, {'iso...  Released   
2           [{'iso_639_1': 'en', 'name': 'English'}]  Released   
3           [{'iso_639_1': 'en', 'name': 'English'}]  Released   
4           [{'iso_639_1': 'en', 'name': 'English'}]  Released   

                                             tagline  \
0                                                NaN   
1          Roll the dice and unleash the excitement!   
2  Still Yelling. Still Fighting. Still Ready for...   
3  Friends are the people who let you be yourself...   
4  Just When His World Is Back To Normal... He's ...   

                         title  video vote_average vote_count  
0                    Toy Story  False          7.7       5415  
1                      Jumanji  False          6.9       2413  
2             Grumpier Old Men  False          6.5         92  
3            Waiting to Exhale  False          6.1         34  
4  Father of the Bride Part II  False          5.7        173  

[5 rows x 25 columns]

In [4]:
# dimensions of our data frame
movies_data.shape

(14999, 25)

In [5]:
# selecting the features for the recommendation
selected_features = ['genres','belongs_to_collection','tagline','spoken_languages']
print(selected_features)

['genres', 'belongs_to_collection', 'tagline', 'spoken_languages']


In [6]:
# Replacing the Unknown values(null values) with null string
for feature in selected_features:
  movies_data[feature] = movies_data[feature].fillna('')

In [7]:
# combining all the features
combined_features = movies_data['genres']+' '+movies_data['belongs_to_collection']+' '+movies_data['tagline']+' '+movies_data['spoken_languages']

In [8]:
print(combined_features)

0        [{'id': 16, 'name': 'Animation'}, {'id': 35, '...
1        [{'id': 12, 'name': 'Adventure'}, {'id': 14, '...
2        [{'id': 10749, 'name': 'Romance'}, {'id': 35, ...
3        [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...
4        [{'id': 35, 'name': 'Comedy'}] {'id': 96871, '...
                               ...                        
14994    [{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...
14995    [{'id': 80, 'name': 'Crime'}, {'id': 53, 'name...
14996    [{'id': 80, 'name': 'Crime'}, {'id': 27, 'name...
14997    [{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...
14998    [{'id': 99, 'name': 'Documentary'}]   [{'iso_6...
Length: 14999, dtype: object


In [9]:
# converting the text data to feature vectors

vectorizer = TfidfVectorizer()

In [10]:
feature_vectors = vectorizer.fit_transform(combined_features)

In [11]:
print(feature_vectors)

  (0, 4331)	0.0520056149595916
  (0, 4309)	0.05200206258379833
  (0, 6125)	0.04364442472605053
  (0, 1512)	0.400040811993079
  (0, 2124)	0.1275117880040584
  (0, 6274)	0.26096749316494955
  (0, 1241)	0.400040811993079
  (0, 8271)	0.1275117880040584
  (0, 3227)	0.13296885866183492
  (0, 9991)	0.18999055710265614
  (0, 10590)	0.3879485314703657
  (0, 24)	0.400040811993079
  (0, 4592)	0.14973251606675772
  (0, 69)	0.1536915331040322
  (0, 3252)	0.08745386020678736
  (0, 776)	0.08751169498855846
  (0, 1857)	0.19018032485860997
  (0, 7447)	0.2120109568134793
  (0, 306)	0.18970750225154293
  (0, 5882)	0.17097119261965424
  (1, 1729)	0.1498802353507514
  (1, 4925)	0.1498802353507514
  (1, 4911)	0.1498802353507514
  (1, 4461)	0.34697713358179105
  (1, 10909)	0.3856119456644116
  :	:
  (14996, 4309)	0.13554575567070343
  (14996, 6125)	0.11376119015996057
  (14996, 7447)	0.44209300822164277
  (14996, 5882)	0.3342331777351357
  (14997, 8240)	0.5226263382178796
  (14997, 8155)	0.5226263382178796
 

In [13]:
similarity = cosine_similarity(feature_vectors)

In [ ]:
print(similarity)

[[1.         0.05083168 0.0332947  ... 0.02749812 0.0304889  0.0072518 ]
 [0.05083168 1.         0.04356836 ... 0.05077045 0.03100979 0.01521198]
 [0.0332947  0.04356836 1.         ... 0.02646984 0.04751623 0.01372603]
 ...
 [0.02749812 0.05077045 0.02646984 ... 1.         0.03481447 0.03546821]
 [0.0304889  0.03100979 0.04751623 ... 0.03481447 1.         0.03098945]
 [0.0072518  0.01521198 0.01372603 ... 0.03546821 0.03098945 1.        ]]


In [14]:
print(similarity.shape)

(14999, 14999)


Getting User Input (Favorite Movie Name) 

In [15]:
# getting the movie name from the user

movie_name = input(' Enter your favourite movie name : ')

 Enter your favourite movie name : batman


In [16]:
# creating a list with all the movie names given in the dataset

list_of_all_titles = movies_data['title'].tolist()
print(list_of_all_titles)

['Toy Story', 'Jumanji', 'Grumpier Old Men', 'Waiting to Exhale', 'Father of the Bride Part II', 'Heat', 'Sabrina', 'Tom and Huck', 'Sudden Death', 'GoldenEye', 'The American President', 'Dracula: Dead and Loving It', 'Balto', 'Nixon', 'Cutthroat Island', 'Casino', 'Sense and Sensibility', 'Four Rooms', 'Ace Ventura: When Nature Calls', 'Money Train', 'Get Shorty', 'Copycat', 'Assassins', 'Powder', 'Leaving Las Vegas', 'Othello', 'Now and Then', 'Persuasion', 'The City of Lost Children', 'Shanghai Triad', 'Dangerous Minds', 'Twelve Monkeys', 'Wings of Courage', 'Babe', 'Carrington', 'Dead Man Walking', 'Across the Sea of Time', 'It Takes Two', 'Clueless', 'Cry, the Beloved Country', 'Richard III', 'Dead Presidents', 'Restoration', 'Mortal Kombat', 'To Die For', 'How To Make An American Quilt', 'Se7en', 'Pocahontas', 'When Night Is Falling', 'The Usual Suspects', 'Guardian Angel', 'Mighty Aphrodite', 'Lamerica', 'The Big Green', 'Georgia', 'Kids of the Round Table', 'Home for the Holida

In [17]:
# finding the close match for the movie name given by the user

find_close_match = difflib.get_close_matches(movie_name, list_of_all_titles)
print(find_close_match)

['Batman', 'Batman', 'Satan']


In [18]:
close_match = find_close_match[0]
print(close_match)

Batman


In [21]:
# finding the index of the movie with title

index_of_the_movie = movies_data[movies_data.title == close_match]['Index'].values[0]
print(index_of_the_movie)

585


In [22]:
# getting the list of similar movies

similarity_score = list(enumerate(similarity[index_of_the_movie]))
print(similarity_score)

[(0, 0.14958311019377749), (1, 0.1832678209143564), (2, 0.0939296632327167), (3, 0.09655327064175587), (4, 0.13153573548926184), (5, 0.10301411949269422), (6, 0.13462227189047302), (7, 0.14158935631603356), (8, 0.09259581874525911), (9, 0.14203530112463544), (10, 0.14583313433491268), (11, 0.11880899772616928), (12, 0.11211125223548499), (13, 0.07639511920080953), (14, 0.07068598303644669), (15, 0.0718313705495887), (16, 0.04646290070462826), (17, 0.06448829147224912), (18, 0.11552770304324804), (19, 0.11253816182483137), (20, 0.12381621401811249), (21, 0.05774453681500596), (22, 0.13634888611923074), (23, 0.14278545482443933), (24, 0.1586508159264895), (25, 0.03465981081160896), (26, 0.10094342546959889), (27, 0.14451208687663233), (28, 0.16903620817125484), (29, 0.07181276602052475), (30, 0.06780026898101642), (31, 0.1803336428228045), (32, 0.12040262160126011), (33, 0.1668480940926438), (34, 0.06499458763514072), (35, 0.1572313827178193), (36, 0.10729861802046371), (37, 0.0479529710

In [23]:
# sorting all the similar movies based on their similarity score

sorted_similar_movies = sorted(similarity_score, key = lambda x:x[1], reverse = True) 
print(sorted_similar_movies)

[(585, 1.0), (150, 0.5953196774159081), (1328, 0.5831766435975491), (1491, 0.5562273561710035), (13586, 0.3028397695126688), (13021, 0.2965035921630238), (6693, 0.29082358567491406), (14288, 0.28961874047434233), (11872, 0.285651530577372), (9289, 0.2840531778757331), (14652, 0.27673714083163675), (11218, 0.2731007623953092), (7459, 0.2727007372841177), (728, 0.269218047310273), (5199, 0.269218047310273), (12735, 0.269218047310273), (11420, 0.2690729551432539), (10409, 0.2669668297652705), (11067, 0.2653077281536933), (6537, 0.26423246320288707), (7145, 0.26328959582791267), (9163, 0.2625076946271948), (5999, 0.26059217431255133), (11833, 0.2602740373582506), (9198, 0.2596387647807579), (477, 0.2595931749111616), (3772, 0.2595931749111616), (6179, 0.25913418667950855), (11832, 0.2587205057236392), (13917, 0.2580761238831673), (14432, 0.25746375224217777), (10709, 0.25733400920776306), (10279, 0.2560390723414876), (14513, 0.2560390723414876), (10332, 0.2548457675935482), (11220, 0.25436

In [24]:
# print the name of similar movies based on the index

print('Movies suggested for you : \n')

i = 1

for movie in sorted_similar_movies:
  index = movie[0]
  title_from_index = movies_data[movies_data.index==index]['title'].values[0]
  if (i<30):
    print(i, '.',title_from_index)
    i+=1

Movies suggested for you : 

1 . Batman
2 . Batman Forever
3 . Batman Returns
4 . Batman & Robin
5 . The Exterminating Angels
6 . Two Worlds
7 . Images
8 . India Song
9 . The Blue Bird
10 . Blueberry
11 . Detention
12 . The Red Balloon
13 . The Secret Life of Walter Mitty
14 . Force of Evil
15 . Bob le Flambeur
16 . Dog Day
17 . Celine and Julie Go Boating
18 . Münchhausen
19 . Superman Returns
20 . The Medallion
21 . The Code
22 . Vidocq
23 . Sword of the Valiant: The Legend of Sir Gawain and the Green Knight
24 . The Librarian: Quest for the Spear
25 . Beautiful Joe
26 . Killing Zoe
27 . The Way of the Gun
28 . Swords of Blood
29 . The Librarian: Return to King Solomon's Mines


In [27]:
movie_name = input(' Enter your favourite movie name : ')

list_of_all_titles = movies_data['title'].tolist()

find_close_match = difflib.get_close_matches(movie_name, list_of_all_titles)

close_match = find_close_match[0]

index_of_the_movie = movies_data[movies_data.title == close_match]['Index'].values[0]

similarity_score = list(enumerate(similarity[index_of_the_movie]))

sorted_similar_movies = sorted(similarity_score, key = lambda x:x[1], reverse = True) 

print('Movies suggested for you : \n')

i = 1

for movie in sorted_similar_movies:
  index = movie[0]
  title_from_index = movies_data[movies_data.index==index]['title'].values[0]
  if (i<30):
    print(i, '.',title_from_index)
    i+=1

 Enter your favourite movie name : toy story
Movies suggested for you : 

1 . Toy Story
2 . Toy Story 2
3 . The Looney, Looney, Looney Bugs Bunny Movie
4 . The Ugly Duckling and Me!
5 . The Tigger Movie
6 . The Little Drummer Boy
7 . Merry Madagascar
8 . So Dear to My Heart
9 . TMNT
10 . Up
11 . Creature Comforts
12 . The Chipmunk Adventure
13 . Pinocchio and the Emperor of the Night
14 . Shrek the Halls
15 . Will Vinton's Claymation Christmas Celebration
16 . Is It Fall Yet?
17 . Aqua Teen Hunger Force Colon Movie Film for Theaters
18 . Immigrants (L.A. Dolce Vita)
19 . I Married a Strange Person!
20 . The Point!
21 . Winnie the Pooh and the Blustery Day
22 . Melody Time
23 . Fallen Art
24 . Is It College Yet?
25 . VeggieTales: The Pirates Who Don't Do Anything
26 . A Monkey's Tale
27 . G.I. Joe: The Movie
28 . The Air Up There
29 . Fathers' Day
