<a href="https://colab.research.google.com/github/Kedhar034/Recommedation-system-project/blob/main/Recommendation_system_using_ML_with_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing dependencies


In [ ]:
import numpy as np
import pandas as pd
import difflib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
# loading from data from the csv file to apandas dataframe
movies_data= pd.read_csv('/content/drive/MyDrive/Recommendation system/movies.csv')


In [ ]:
# printing the first 5 rows of dataframe
movies_data.head()

index     budget                                    genres  \
0      0  237000000  Action Adventure Fantasy Science Fiction   
1      1  300000000                  Adventure Fantasy Action   
2      2  245000000                    Action Adventure Crime   
3      3  250000000               Action Crime Drama Thriller   
4      4  260000000          Action Adventure Science Fiction   

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   
3            http://www.thedarkknightrises.com/   49026   
4          http://movies.disney.com/john-carter   49529   

                                            keywords original_language  \
0  culture clash future space war space colony so...                en   
1  ocean drug abuse exotic island east india trad...                en   
2         spy based on novel secret agent sequel mi6                en   
3  dc comics crime fighter terrorist secret ident...                en   
4  based on novel mars medallion space travel pri...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                            overview  popularity  ... runtime  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577  ...   162.0   
1  Captain Barbossa, long believed to be dead, ha...  139.082615  ...   169.0   
2  A cryptic message from Bond’s past sends him o...  107.376788  ...   148.0   
3  Following the death of District Attorney Harve...  112.312950  ...   165.0   
4  John Carter is a war-weary, former military ca...   43.926995  ...   132.0   

                                    spoken_languages    status  \
0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1           [{"iso_639_1": "en", "name": "English"}]  Released   
2  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released   
3           [{"iso_639_1": "en", "name": "English"}]  Released   
4           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   
2                           A Plan No One Escapes   
3                                 The Legend Ends   
4            Lost in our world, found in another.   

                                      title vote_average vote_count  \
0                                    Avatar          7.2      11800   
1  Pirates of the Caribbean: At World's End          6.9       4500   
2                                   Spectre          6.3       4466   
3                     The Dark Knight Rises          7.6       9106   
4                               John Carter          6.1       2124   

                                                cast  \
0  Sam Worthington Zoe Saldana Sigourney Weaver S...   
1  Johnny Depp Orlando Bloom Keira Knightley Stel...   
2  Daniel Craig Christoph Waltz L\u00e9a Seydoux ...   
3  Christian Bale Michael Caine Gary Oldman Anne ...   
4  Taylor Kitsch Lynn Collins Samantha Morton Wil...   

                                                crew           director  
0  [{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...      James Cameron  
1  [{'name': 'Dariusz Wolski', 'gender': 2, 'depa...     Gore Verbinski  
2  [{'name': 'Thomas Newman', 'gender': 2, 'depar...         Sam Mendes  
3  [{'name': 'Hans Zimmer', 'gender': 2, 'departm...  Christopher Nolan  
4  [{'name': 'Andrew Stanton', 'gender': 2, 'depa...     Andrew Stanton  

[5 rows x 24 columns]

In [ ]:
# dimensions of our data frame
movies_data.shape

(4803, 24)

In [ ]:
# selecting the features for the recommendation
selected_features = ['genres','keywords','overview','tagline','cast','director']
print(selected_features)

['genres', 'keywords', 'overview', 'tagline', 'cast', 'director']


In [ ]:
# Replacing the Unknown values(null values) with null string
for feature in selected_features:
  movies_data[feature] = movies_data[feature].fillna('')

In [ ]:
# combining all the features
combined_features = movies_data['genres']+' '+movies_data['keywords']+' '+movies_data['overview']+' '+movies_data['tagline']+' '+movies_data['cast']+' '+movies_data['director']

In [ ]:
print(combined_features)

0       [{"id": 28, "name": "Action"}, {"id": 12, "nam...
1       [{"id": 12, "name": "Adventure"}, {"id": 14, "...
2       [{"id": 28, "name": "Action"}, {"id": 12, "nam...
3       [{"id": 28, "name": "Action"}, {"id": 80, "nam...
4       [{"id": 28, "name": "Action"}, {"id": 12, "nam...
                              ...                        
4798    [{"id": 28, "name": "Action"}, {"id": 80, "nam...
4799    [{"id": 35, "name": "Comedy"}, {"id": 10749, "...
4800    [{"id": 35, "name": "Comedy"}, {"id": 18, "nam...
4801    [] [] When ambitious New York attorney Sam is ...
4802    [{"id": 99, "name": "Documentary"}] [{"id": 15...
Length: 4803, dtype: object


In [ ]:
# converting the text data to feature vectors

vectorizer = TfidfVectorizer()

In [ ]:
feature_vectors = vectorizer.fit_transform(combined_features)

In [ ]:
print(feature_vectors)

  (0, 4288)	0.13213124585063996
  (0, 14180)	0.08418056281586364
  (0, 23134)	0.1498786462809525
  (0, 17784)	0.12285843797047787
  (0, 15569)	0.171366691592621
  (0, 25868)	0.11590870590502833
  (0, 29614)	0.15064979633862852
  (0, 24802)	0.158925784923944
  (0, 23578)	0.16802034155542864
  (0, 30543)	0.15064979633862852
  (0, 30145)	0.18243919685121024
  (0, 23619)	0.11047375838269538
  (0, 19410)	0.0318696249813729
  (0, 30121)	0.07272849549697494
  (0, 9065)	0.14505772980982928
  (0, 5245)	0.16506865163441015
  (0, 1014)	0.12285843797047787
  (0, 1243)	0.05270709034262741
  (0, 21523)	0.1665010643166998
  (0, 1281)	0.03195190270050669
  (0, 19650)	0.1612055740237117
  (0, 10368)	0.13848277654301597
  (0, 2974)	0.09974129089792806
  (0, 27515)	0.14569220419090678
  (0, 2685)	0.09805341831299116
  :	:
  (4802, 27153)	0.05940079357098276
  (4802, 19243)	0.061349419053434766
  (4802, 11941)	0.07829183421073846
  (4802, 29680)	0.07735547381237222
  (4802, 9346)	0.07104321122746965
  (48

In [ ]:
similarity = cosine_similarity(feature_vectors)

In [ ]:
print(similarity)

[[1.         0.05083168 0.0332947  ... 0.02749812 0.0304889  0.0072518 ]
 [0.05083168 1.         0.04356836 ... 0.05077045 0.03100979 0.01521198]
 [0.0332947  0.04356836 1.         ... 0.02646984 0.04751623 0.01372603]
 ...
 [0.02749812 0.05077045 0.02646984 ... 1.         0.03481447 0.03546821]
 [0.0304889  0.03100979 0.04751623 ... 0.03481447 1.         0.03098945]
 [0.0072518  0.01521198 0.01372603 ... 0.03546821 0.03098945 1.        ]]


In [ ]:
print(similarity.shape)

(4803, 4803)


Getting User Input (Favorite Movie Name) 

In [ ]:
# getting the movie name from the user

movie_name = input(' Enter your favourite movie name : ')

 Enter your favourite movie name : Toy story


In [ ]:
# creating a list with all the movie names given in the dataset

list_of_all_titles = movies_data['title'].tolist()
print(list_of_all_titles)

['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre', 'The Dark Knight Rises', 'John Carter', 'Spider-Man 3', 'Tangled', 'Avengers: Age of Ultron', 'Harry Potter and the Half-Blood Prince', 'Batman v Superman: Dawn of Justice', 'Superman Returns', 'Quantum of Solace', "Pirates of the Caribbean: Dead Man's Chest", 'The Lone Ranger', 'Man of Steel', 'The Chronicles of Narnia: Prince Caspian', 'The Avengers', 'Pirates of the Caribbean: On Stranger Tides', 'Men in Black 3', 'The Hobbit: The Battle of the Five Armies', 'The Amazing Spider-Man', 'Robin Hood', 'The Hobbit: The Desolation of Smaug', 'The Golden Compass', 'King Kong', 'Titanic', 'Captain America: Civil War', 'Battleship', 'Jurassic World', 'Skyfall', 'Spider-Man 2', 'Iron Man 3', 'Alice in Wonderland', 'X-Men: The Last Stand', 'Monsters University', 'Transformers: Revenge of the Fallen', 'Transformers: Age of Extinction', 'Oz: The Great and Powerful', 'The Amazing Spider-Man 2', 'TRON: Legacy', 'Cars 2', 'Green Lant

In [ ]:
# finding the close match for the movie name given by the user

find_close_match = difflib.get_close_matches(movie_name, list_of_all_titles)
print(find_close_match)

['Toy Story', 'Toy Story 3', 'Toy Story 2']


In [ ]:
close_match = find_close_match[0]
print(close_match)

Toy Story


In [ ]:
# finding the index of the movie with title

index_of_the_movie = movies_data[movies_data.title == close_match]['index'].values[0]
print(index_of_the_movie)

1541


In [ ]:
# getting the list of similar movies

similarity_score = list(enumerate(similarity[index_of_the_movie]))
print(similarity_score)

[(0, 0.01108295608214383), (1, 0.014879861095367817), (2, 0.008716313252970505), (3, 0.016247730008295557), (4, 0.025611008602864194), (5, 0.018355093775903095), (6, 0.031316042673769084), (7, 0.029400271272277567), (8, 0.018606839760728265), (9, 0.005962631795135075), (10, 0.03531817977543603), (11, 0.01517697334358016), (12, 0.006214457239062075), (13, 0.023204615076475935), (14, 0.039323978434230536), (15, 0.028459657195652785), (16, 0.015068265052831346), (17, 0.027619576401467776), (18, 0.04487343045362914), (19, 0.027598752512668738), (20, 0.03246346497256082), (21, 0.03280372781913691), (22, 0.019877598279083593), (23, 0.007352359745553286), (24, 0.027014529439219254), (25, 0.021402714939356415), (26, 0.007519760612238353), (27, 0.03166451133282638), (28, 0.008956405438132045), (29, 0.01834222979280717), (30, 0.029199835833325194), (31, 0.020711008451593054), (32, 0.037489197816760536), (33, 0.007243470163007513), (34, 0.04649003245680428), (35, 0.013404514109365388), (36, 0.020

In [ ]:
# sorting all the similar movies based on their similarity score

sorted_similar_movies = sorted(similarity_score, key = lambda x:x[1], reverse = True) 
print(sorted_similar_movies)

[(1541, 1.0000000000000002), (343, 0.4226008697344497), (42, 0.36494102940623774), (1779, 0.16436027634289735), (4073, 0.156255757777995), (2479, 0.1493097430768244), (4108, 0.14303399447251114), (2217, 0.13753397630175684), (3739, 0.13403906178258893), (2488, 0.13355643686573374), (4075, 0.13018942304630934), (4141, 0.12862738776853633), (3754, 0.12306556535137293), (2065, 0.12101948489990477), (2349, 0.12093346663827088), (2869, 0.12084318791043104), (2569, 0.11732950796264854), (837, 0.11600458749498155), (2213, 0.11156766888474738), (1805, 0.1086323704525035), (2376, 0.10711078939754849), (1191, 0.09761861812931373), (3379, 0.09625367113655293), (891, 0.09442815157493768), (1579, 0.08879513098946587), (1612, 0.08703614474881516), (2600, 0.08653549445271488), (822, 0.08522717574744194), (1086, 0.08402541371496913), (2761, 0.08248878655380418), (3140, 0.08215258000179075), (3383, 0.07930200519792006), (3065, 0.07889163451190719), (2851, 0.07719025165875862), (496, 0.07646718322881355

In [ ]:
# print the name of similar movies based on the index

print('Movies suggested for you : \n')

i = 1

for movie in sorted_similar_movies:
  index = movie[0]
  title_from_index = movies_data[movies_data.index==index]['title'].values[0]
  if (i<30):
    print(i, '.',title_from_index)
    i+=1

Movies suggested for you : 

1 . Toy Story
2 . Toy Story 2
3 . Toy Story 3
4 . The 40 Year Old Virgin
5 . Sleeper
6 . Radio Days
7 . In the Shadow of the Moon
8 . Everyone Says I Love You
9 . Annie Hall
10 . Hollywood Ending
11 . Everything You Always Wanted to Know About Sex *But Were Afraid to Ask
12 . Bananas
13 . Scoop
14 . To Rome with Love
15 . Small Time Crooks
16 . For Your Consideration
17 . Match Point
18 . Free Birds
19 . Deconstructing Harry
20 . The Curse of the Jade Scorpion
21 . Anything Else
22 . Small Soldiers
23 . Factory Girl
24 . Man on the Moon
25 . Midnight in Paris
26 . Larry Crowne
27 . New York Stories
28 . Maid in Manhattan
29 . Aliens in the Attic


In [ ]:
movie_name = input(' Enter your favourite movie name : ')

list_of_all_titles = movies_data['title'].tolist()

find_close_match = difflib.get_close_matches(movie_name, list_of_all_titles)

close_match = find_close_match[0]

index_of_the_movie = movies_data[movies_data.title == close_match]['index'].values[0]

similarity_score = list(enumerate(similarity[index_of_the_movie]))

sorted_similar_movies = sorted(similarity_score, key = lambda x:x[1], reverse = True) 

print('Movies suggested for you : \n')

i = 1

for movie in sorted_similar_movies:
  index = movie[0]
  title_from_index = movies_data[movies_data.index==index]['title'].values[0]
  if (i<30):
    print(i, '.',title_from_index)
    i+=1

 Enter your favourite movie name : seven
Movies suggested for you : 

1 . Se7en
2 . City By The Sea
3 . My Soul to Take
4 . Murder by Numbers
5 . Zodiac
6 . The Cell
7 . Seven Pounds
8 . The Bone Collector
9 . Mindhunters
10 . Insomnia
11 . 2:13
12 . Edge of Darkness
13 . Suspect Zero
14 . The Silence of the Lambs
15 . The Raven
16 . The Frozen Ground
17 . Outbreak
18 . The Beyond
19 . Copycat
20 . Along Came a Spider
21 . Sin City
22 . Skyfall
23 . Club Dread
24 . Saw IV
25 . Untraceable
26 . Misconduct
27 . Halloween: Resurrection
28 . Tango & Cash
29 . Bedazzled
